### ISSUE TITLE
Phalcon 2.x

### ISSUE THREAD

**Issue by sergeyklay** [vanchelo/phalcon-mailer#4]
Привет!
Как насчёт сабжекта? :)

**Comment by ErickSkrauch** [comment]
Я не тестил, но теоретически проблем не должно быть.

**Comment by sergeyklay** [comment]
https://github.com/vanchelo/phalcon-mailer/blob/master/src/Mailer.php#L369

**Comment by ErickSkrauch** [comment]
Это ведь GitHub - PR всегда приветствуются ))

**Comment by sergeyklay** [comment]
Ну дк PR сломает совместимость с 1.3.х

**Comment by ErickSkrauch** [comment]
Ну есть вариант выпустить новую версию под номером 2.0.0 и указать в зависимостях пакета требование php-phalcon старше 2.0.0.

**Comment by vanchelo** [comment]
Ага, давайте новую версию запилю)

**Comment by vanchelo** [comment]
Пофикшено))

**Comment by sergeyklay** [comment]
:+1:
